### ISSUE TITLE
SMTPAuthenticationError when joining ride

### ISSUE THREAD

**Issue by frozenpandaman** [aspc/5C-Ride-Share#8]
![screen shot 2015-11-02 at 2 21 11](https://cloud.githubusercontent.com/assets/7245874/10889425/cf938c98-8146-11e5-8908-d4d68bb7f75c.png)

encountered when trying to join [this ride](http://5crideshare.com/rides/2402). i seem to be join (and leave) other rides fine.

**Comment by alokedesai** [comment]
Stack trace:

```
2015-11-02T22:06:24.574013+00:00 app[web.1]: Started GET "/rides/join?id=2402" for 134.173.78.2 at 2015-11-02 22:06:24 +0000
2015-11-02T22:06:24.591251+00:00 app[web.1]:   Rendered user_mailer/new_rider_email.text.erb (0.3ms)
2015-11-02T22:06:24.577122+00:00 app[web.1]:   Parameters: {"id"=>"2402"}
2015-11-02T22:06:24.590660+00:00 app[web.1]:   Rendered user_mailer/new_rider_email.html.erb (0.3ms)
2015-11-02T22:06:24.577100+00:00 app[web.1]: Processing by RidesController#join as HTML
2015-11-02T22:06:24.865558+00:00 heroku[router]: at=info method=GET path="/rides/join?id=2402" host=5crideshare.com request_id=7ee0bbb8-6137-4a83-bded-70b077812566 fwd="134.173.78.2" dyno=web.1 connect=1ms service=291ms status=500 bytes=1048
2015-11-02T22:06:24.857796+00:00 app[web.1]:
2015-11-02T22:06:24.857800+00:00 app[web.1]: Sent mail to gallahergh@gmail.com (259ms)
2015-11-02T22:06:24.858068+00:00 app[web.1]: Completed 500 Internal Server Error in 281ms
2015-11-02T22:06:24.859853+00:00 app[web.1]:
2015-11-02T22:06:24.859857+00:00 app[web.1]: ):
2015-11-02T22:06:24.859856+00:00 app[web.1]: Net::SMTPAuthenticationError (535-5.7.8 Username and Password not accepted. Learn more at
2015-11-02T22:06:24.859858+00:00 app[web.1]:   app/controllers/rides_controller.rb:92:in `join'
2015-11-02T22:06:24.859859+00:00 app[web.1]:
2015-11-02T22:06:24.859858+00:00 app[web.1]:   app/controllers/rides_controller.rb:94:in `block in join'
2015-11-02T22:06:24.859859+00:00 app[web.1]:
```

**Comment by KentShikama** [comment]
Fixed with dd9120855b72d2549c670e32e090a10730d489d8

**Comment by mattdahl** [comment]
@theworldbright What was the problem here? Why was just this ride affected?

**Comment by alokedesai** [comment]
@mattdahl I assumed because this user was one of the few who turned on email notifications

**Comment by alokedesai** [comment]
Every single ride this user created had the same problems.

**Comment by KentShikama** [comment]
Yup just as Aloke mentioned. Essentially the authentication credentials for `5crideshare@gmail.com` were changed (hacked?). We are now using `aspcrideshare@gmail.com`.

**Comment by jessepollak** [comment]
whoops could have been me accidentally a while ago, sorry y'all!

ps awesome to see work being done on this thing :)

**Comment by mattdahl** [comment]
Cool, can you add the credentials for that account to our docs?
